image: Visual Studio 2017
environment:
  FORCE_COLOR: 1
  nodejs_version: "14"
  matrix:
  - TYPESCRIPT: typescript@3.9.3
  - TYPESCRIPT: typescript@next
  - TYPESCRIPT: typescript@3.8.2
  - TYPESCRIPT: typescript@3.7.4
  - TYPESCRIPT: typescript@3.6.3
  
install:
  - ps: Install-Product node $env:nodejs_version
  - yarn install
  - yarn build
  - yarn lint
  - yarn add %TYPESCRIPT%
test_script:
  - node --version
  - yarn --version
  - yarn test
build: off
